import tkinter as tk
from tkinter import ttk, messagebox
import oracledb

# --------------------------
# Configuración de Oracle
# --------------------------
# Rellena con tus credenciales reales
USER ="system"
PASSWORD ="Tapiero123"
DSN ="localhost:1521/orcl" #ajusta a tu base de datos oracle

# --------------------------
# conexion y tabla .
# --------------------------
def inicializar_bd():
    try:
        conn= oracledb.connect(user=USER, password=PASSWORD, dsn=DSN)
        cur= conn.cursor()
        cur.execute("""
            CREATE TABLE equipos_futbol(
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre VARCHAR2(100)
            )
        """)
        conn.commit()
        cur.close()
        conn.close()
    except oracledb.DatabaseError as e:
        #si la tabla ya existe, ignoramos .
        if "ORA-00955" in str(e):
            pass
        else:
            raise
    
def insertar_equipo(nombre):
    conn = oracledb.connect(user=USER, password=PASSWORD, dsn=DSN)
    cur = conn.cursor()
    cur.execute("INSERT INTO equipos_futbol (nombre) VALUES (:1)", [nombre])
    conn.commit()
    cur.close()
    conn.close()

def obtener_equipos():
    conn = oracledb.connect(user=USER, password=PASSWORD, dsn=DSN)
    cur = conn.cursor()
    cur.execute("SELECT nombre FROM equipos_futbol ORDER BY id")
    equipos =[row[0] for row in cur.fetchall()]
    cur.close()
    conn.close()
    return equipos

# --------------------------
# Interfaz grafica .
# --------------------------