-- ========================================
-- Script: Creación y carga de equipos_futbol
-- Autor: Giovanny & ChatGPT
-- ========================================

-- Eliminamos la tabla si ya existe (para evitar conflictos)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE equipos_futbol';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- Creamos la tabla equipos_futbol
CREATE TABLE equipos_futbol (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL
);

-- ========================================
-- Inserción de 78 equipos de fútbol
-- ========================================

-- España
INSERT INTO equipos_futbol (nombre) VALUES ('FC Barcelona');
INSERT INTO equipos_futbol (nombre) VALUES ('Real Madrid');
INSERT INTO equipos_futbol (nombre) VALUES ('Atlético de Madrid');
INSERT INTO equipos_futbol (nombre) VALUES ('Sevilla FC');
INSERT INTO equipos_futbol (nombre) VALUES ('Valencia CF');
INSERT INTO equipos_futbol (nombre) VALUES ('Real Betis');
INSERT INTO equipos_futbol (nombre) VALUES ('Villarreal CF');
INSERT INTO equipos_futbol (nombre) VALUES ('Athletic Club');
INSERT INTO equipos_futbol (nombre) VALUES ('Real Sociedad');
INSERT INTO equipos_futbol (nombre) VALUES ('Getafe CF');

-- Inglaterra
INSERT INTO equipos_futbol (nombre) VALUES ('Manchester United');
INSERT INTO equipos_futbol (nombre) VALUES ('Manchester City');
INSERT INTO equipos_futbol (nombre) VALUES ('Liverpool FC');
INSERT INTO equipos_futbol (nombre) VALUES ('Chelsea FC');
INSERT INTO equipos_futbol (nombre) VALUES ('Arsenal FC');
INSERT INTO equipos_futbol (nombre) VALUES ('Tottenham Hotspur');
INSERT INTO equipos_futbol (nombre) VALUES ('Leicester City');
INSERT INTO equipos_futbol (nombre) VALUES ('West Ham United');
INSERT INTO equipos_futbol (nombre) VALUES ('Everton FC');
INSERT INTO equipos_futbol (nombre) VALUES ('Leeds United');

-- Italia
INSERT INTO equipos_futbol (nombre) VALUES ('Juventus');
INSERT INTO equipos_futbol (nombre) VALUES ('AC Milan');
INSERT INTO equipos_futbol (nombre) VALUES ('Inter de Milán');
INSERT INTO equipos_futbol (nombre) VALUES ('AS Roma');
INSERT INTO equipos_futbol (nombre) VALUES ('SS Lazio');
INSERT INTO equipos_futbol (nombre) VALUES ('Napoli');
INSERT INTO equipos_futbol (nombre) VALUES ('Fiorentina');
INSERT INTO equipos_futbol (nombre) VALUES ('Torino FC');
INSERT INTO equipos_futbol (nombre) VALUES ('Atalanta');
INSERT INTO equipos_futbol (nombre) VALUES ('Sampdoria');

-- Alemania
INSERT INTO equipos_futbol (nombre) VALUES ('Bayern Múnich');
INSERT INTO equipos_futbol (nombre) VALUES ('Borussia Dortmund');
INSERT INTO equipos_futbol (nombre) VALUES ('RB Leipzig');
INSERT INTO equipos_futbol (nombre) VALUES ('Bayer Leverkusen');
INSERT INTO equipos_futbol (nombre) VALUES ('Schalke 04');
INSERT INTO equipos_futbol (nombre) VALUES ('Borussia Mönchengladbach');
INSERT INTO equipos_futbol (nombre) VALUES ('VfL Wolfsburgo');
INSERT INTO equipos_futbol (nombre) VALUES ('Eintracht Frankfurt');

-- Francia
INSERT INTO equipos_futbol (nombre) VALUES ('Paris Saint-Germain');
INSERT INTO equipos_futbol (nombre) VALUES ('Olympique de Marsella');
INSERT INTO equipos_futbol (nombre) VALUES ('Olympique de Lyon');
INSERT INTO equipos_futbol (nombre) VALUES ('AS Mónaco');
INSERT INTO equipos_futbol (nombre) VALUES ('Lille OSC');
INSERT INTO equipos_futbol (nombre) VALUES ('Stade Rennais');
INSERT INTO equipos_futbol (nombre) VALUES ('OGC Niza');
INSERT INTO equipos_futbol (nombre) VALUES ('Saint-Étienne');

-- Argentina & Brasil
INSERT INTO equipos_futbol (nombre) VALUES ('Boca Juniors');
INSERT INTO equipos_futbol (nombre) VALUES ('River Plate');
INSERT INTO equipos_futbol (nombre) VALUES ('Independiente');
INSERT INTO equipos_futbol (nombre) VALUES ('Racing Club');
INSERT INTO equipos_futbol (nombre) VALUES ('San Lorenzo');
INSERT INTO equipos_futbol (nombre) VALUES ('Flamengo');
INSERT INTO equipos_futbol (nombre) VALUES ('Palmeiras');
INSERT INTO equipos_futbol (nombre) VALUES ('Sao Paulo');
INSERT INTO equipos_futbol (nombre) VALUES ('Corinthians');
INSERT INTO equipos_futbol (nombre) VALUES ('Santos FC');

-- Colombia
INSERT INTO equipos_futbol (nombre) VALUES ('Atlético Nacional');
INSERT INTO equipos_futbol (nombre) VALUES ('Millonarios');
INSERT INTO equipos_futbol (nombre) VALUES ('América de Cali');
INSERT INTO equipos_futbol (nombre) VALUES ('Deportivo Cali');
INSERT INTO equipos_futbol (nombre) VALUES ('Junior de Barranquilla');

-- México
INSERT INTO equipos_futbol (nombre) VALUES ('Club América');
INSERT INTO equipos_futbol (nombre) VALUES ('Chivas Guadalajara');
INSERT INTO equipos_futbol (nombre) VALUES ('Cruz Azul');
INSERT INTO equipos_futbol (nombre) VALUES ('Pumas UNAM');
INSERT INTO equipos_futbol (nombre) VALUES ('Monterrey');
INSERT INTO equipos_futbol (nombre) VALUES ('Tigres UANL');

-- Países Bajos, Escocia y Turquía
INSERT INTO equipos_futbol (nombre) VALUES ('Ajax Ámsterdam');
INSERT INTO equipos_futbol (nombre) VALUES ('PSV Eindhoven');
INSERT INTO equipos_futbol (nombre) VALUES ('Feyenoord');
INSERT INTO equipos_futbol (nombre) VALUES ('Celtic FC');
INSERT INTO equipos_futbol (nombre) VALUES ('Rangers FC');
INSERT INTO equipos_futbol (nombre) VALUES ('Galatasaray');
INSERT INTO equipos_futbol (nombre) VALUES ('Fenerbahçe');
INSERT INTO equipos_futbol (nombre) VALUES ('Besiktas');

-- Confirmamos los cambios .
COMMIT;

SELECT * FROM equipos_futbol;